### PR TITLE
add support for enterprise binaries

### PR DESCRIPTION
**Pull request by ykhemani**

### CODE REVIEW

**Comment by kpenfound** [comment]
Hi @ykhemani , thanks for the contribution! We have a few things that need to get wired behind-the-scenes to get these formulae automatically updated, but the formulae themselves look great.

We're on the fence about `*-ent` vs `*-enterprise` for the formula names, so I'll get back to you on that.

`consul-template` and `envconsul` may not be compatible with our automatic formula update system, so I'll have to get back to you on that as well.

For now, this looks good, just hang on while I follow up on those items! Thanks

**Comment by sc250024** [comment]
Was there any progress on this? I would like this feature as well, but it seems that this PR is now very stale.

**Comment by zaid-hc** [comment]
+1

**Comment by mdeggies** [comment]
Hey everyone- This changeset is currently being reviewed over in https://github.com/hashicorp/homebrew-tap/pull/181. Please follow along there for updates!

**Pull request closed without merging**
